version: '3.9'
services:
  django:
    build: .
    command: python3 ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:14
    env_file:
      - .env
    environment:
      - HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
